<template>
<div>
  <v-system-bar 
    color="grey" 
    text-center>
    <v-row
      v-row
      align="center"
      justify="center"
      ><span>v-system-bar</span>
    </v-row> 
  </v-system-bar>
</div>
</template>